-- Seed homepage content into admin_settings
-- These values are editable from Admin > Content & Marketing > Frontend Content

INSERT INTO admin_settings (setting_key, setting_value, setting_type, description) VALUES
  ('hero_heading', 'Transform Spending into Ownership', 'content', 'Homepage hero heading'),
  ('hero_subheading', 'Kamioi automatically rounds up your everyday purchases and invests the spare change into real stocks. Turn every swipe into a step toward building wealth.', 'content', 'Homepage hero subheading'),
  ('hero_cta_text', 'Start Investing Free', 'content', 'Homepage hero CTA button text'),
  ('hero_cta_link', '/register', 'content', 'Homepage hero CTA button link'),
  ('trust_badge_1', 'No minimum investment', 'content', 'Trust badge 1'),
  ('trust_badge_2', 'Bank-level encryption', 'content', 'Trust badge 2'),
  ('trust_badge_3', 'Cancel anytime', 'content', 'Trust badge 3'),
  ('features_heading', 'How your spending builds wealth', 'content', 'Features section heading'),
  ('feature_1', 'Automatic Round-Ups', 'content', 'Feature 1 title'),
  ('feature_1_desc', 'Every purchase is rounded up to the nearest dollar. The spare change is automatically invested into your portfolio.', 'content', 'Feature 1 description'),
  ('feature_2', 'Smart Stock Matching', 'content', 'Feature 2 title'),
  ('feature_2_desc', 'Your purchases are automatically matched to relevant stocks. Buy coffee, own coffee company shares — your spending drives your portfolio.', 'content', 'Feature 2 description'),
  ('feature_3', 'Goal-Based Investing', 'content', 'Feature 3 title'),
  ('feature_3_desc', 'Set savings goals and track your progress. Your strategy adjusts automatically to help you reach them faster.', 'content', 'Feature 3 description'),
  ('steps_heading', 'Start in under 2 minutes', 'content', 'How it works section heading'),
  ('step_1_title', 'Create Your Account', 'content', 'Step 1 title'),
  ('step_1_desc', 'Sign up in seconds with just your email. Choose Individual, Family, or Business.', 'content', 'Step 1 description'),
  ('step_2_title', 'Connect Your Cards', 'content', 'Step 2 title'),
  ('step_2_desc', 'Link your debit or credit cards securely. We use bank-level encryption to protect your data.', 'content', 'Step 2 description'),
  ('step_3_title', 'Watch Your Wealth Grow', 'content', 'Step 3 title'),
  ('step_3_desc', 'Every purchase rounds up automatically. Your spare change is invested into real stocks.', 'content', 'Step 3 description'),
  ('stat_1_value', '$0', 'content', 'Stat 1 value'),
  ('stat_1_label', 'Minimum to start', 'content', 'Stat 1 label'),
  ('stat_2_value', '3', 'content', 'Stat 2 value'),
  ('stat_2_label', 'Account types', 'content', 'Stat 2 label'),
  ('stat_3_value', '24/7', 'content', 'Stat 3 value'),
  ('stat_3_label', 'Portfolio access', 'content', 'Stat 3 label'),
  ('stat_4_value', 'Auto', 'content', 'Stat 4 value'),
  ('stat_4_label', 'Stock matching', 'content', 'Stat 4 label'),
  ('cta_heading', 'Ready to start building wealth?', 'content', 'CTA banner heading'),
  ('cta_subtext', 'Start investing your spare change today. No minimum balance, no hidden fees.', 'content', 'CTA banner subtext'),
  ('cta_button_text', 'Create Free Account', 'content', 'CTA banner button text'),
  ('app_store_url', '#', 'content', 'Apple App Store URL (# = coming soon)'),
  ('play_store_url', '#', 'content', 'Google Play Store URL (# = coming soon)'),
  ('app_section_heading', 'Get the Kamioi App', 'content', 'App download section heading'),
  ('app_section_subtext', 'Invest on the go. Download Kamioi for iOS and Android — coming soon.', 'content', 'App download section subtext'),
  ('footer_company', 'Kamioi', 'content', 'Footer company name'),
  ('footer_tagline', 'Micro-investing that transforms your everyday spending into stock ownership.', 'content', 'Footer tagline'),
  ('footer_copyright', 'Kamioi. All rights reserved.', 'content', 'Footer copyright text')
ON CONFLICT (setting_key) DO UPDATE SET
  setting_value = EXCLUDED.setting_value,
  setting_type = EXCLUDED.setting_type,
  description = EXCLUDED.description,
  updated_at = NOW();
